# Generated by Django 4.0.4 on 2022-06-08 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields
import products.model_enums
import sizes.model_enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sizes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('gender', django_enumfield.db.fields.EnumField(default=2, enum=sizes.model_enums.GenderOptions)),
                ('clothing_type', django_enumfield.db.fields.EnumField(default=0, enum=products.model_enums.ClothingType)),
                ('image', models.ImageField(upload_to='product_pics')),
                ('image2', models.ImageField(blank=True, upload_to='product_pics')),
                ('image3', models.ImageField(blank=True, upload_to='product_pics')),
                ('image4', models.ImageField(blank=True, upload_to='product_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=products.model_enums.ProductStatus)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sizes.size')),
            ],
        ),
    ]
