# Generated by Django 4.0.4 on 2022-06-08 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import sizes.model_enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sizes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.CharField(blank=True, max_length=30, null=True)),
                ('house_name_number', models.CharField(blank=True, max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=50)),
                ('address_line_2', models.CharField(blank=True, max_length=50)),
                ('town_city', models.CharField(blank=True, max_length=50)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=13)),
                ('gender_preference', django_enumfield.db.fields.EnumField(blank=True, enum=sizes.model_enums.GenderOptions, null=True)),
                ('sizes', models.ManyToManyField(to='sizes.size')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
